# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    JNI_PATH: .
    CORENAME: atari800

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
    
  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
    
  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'
    
################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'
    
  # Nintendo Switch
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'
    
  # PlayStation Portable
  - project: 'libretro-infrastructure/ci-templates'
    file: '/psp-static.yml'
  # PlayStation Vita
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

#Desktop
libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default

libretro-build-windows-x64:
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
    
# Android
android-armeabi-v7a:
  extends:
    - .core-defs
    - .libretro-android-jni-armeabi-v7a

android-arm64-v8a:
  extends:
    - .core-defs
    - .libretro-android-jni-arm64-v8a

android-x86_64:
  extends:
    - .core-defs
    - .libretro-android-jni-x86_64
    
android-x86:
  extends:
    - .core-defs
    - .libretro-android-jni-x86

# Static
libretro-build-libnx-aarch64:
  extends:
    - .core-defs
    - .libretro-libnx-static-retroarch-master

libretro-build-vita:
  extends:
    - .libretro-vita-static-retroarch-master
    - .core-defs
    
libretro-build-psp:
  extends:
    - .libretro-psp-static-retroarch-master
    - .core-defs
